service: sls-backend

provider:
  name: aws
  runtime: nodejs10.x
  profile: youtube
  stage: dev

functions:
  getTodos:
    handler: handler.getTodos
    events:
      - http:
          path: todos
          method: get
